# Generated by Django 5.0.6 on 2024-06-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Price",
                to="auctions.bid",
            ),
        ),
    ]
