# Generated by Django 5.0.6 on 2024-06-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_comment_author_remove_comment_massage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.AddField(
            model_name="listing",
            name="bid",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.bid",
            ),
        ),
    ]
