# Generated by Django 5.0.6 on 2024-06-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_remove_listing_price_listing_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="bid",
            new_name="price",
        ),
    ]
