# Generated by Django 5.0.6 on 2024-06-22 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_rename_bid_listing_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="price",
            new_name="bid",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="imageurl",
            new_name="url",
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watch_listings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
