# Generated by Django 5.0.6 on 2024-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="oid",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="Address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(max_length=50),
        ),
    ]
