# Generated by Django 5.0.6 on 2024-06-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_user_id_user_oid_alter_user_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="oid",
            new_name="uid",
        ),
    ]
