# Generated by Django 5.0.6 on 2024-06-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="isActivate",
            new_name="isActive",
        ),
    ]
